when:
  event: [push, manual]
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  syntax-check:
    image: docker.io/ruby:3.4-slim
    name: Lint Ruby Code
    commands:
      - echo "--- Checking backup.rb syntax..."
      - ruby -c backup.rb
      - echo "--- Checking test_backup_pruning.rb syntax..."
      - ruby -c test_backup_pruning.rb

  test-pruning:
    image: docker.io/ruby:3.4-slim
    name: Run Pruning Logic Tests
    depends_on: [syntax-check]
    commands:
      - ruby test_backup_pruning.rb

  container:
    image: quay.io/buildah/stable:latest
    depends_on: [test-pruning]
    privileged: true
    environment:
      PASSWORD:
        from_secret: forgejo_token
      PASSWORD_GITHUB:
        from_secret: github_login
    commands:
      - export REGISTRY=forgejo.pod.hetmer.net
      - export IMAGE=$REGISTRY/${CI_REPO_OWNER}/${CI_REPO_NAME}:latest
      - buildah login -u "${CI_REPO_OWNER}" -p "$PASSWORD" $REGISTRY
      - buildah bud -t $IMAGE .
      - buildah push $IMAGE
      - buildah login -u totoCZ -p "$PASSWORD_GITHUB" ghcr.io
      - buildah push $IMAGE docker://ghcr.io/totocz/${CI_REPO_NAME}:latest